### ISSUE TITLE
Cannot open "https://beta.unlimapps.com"

### ISSUE THREAD

**Issue by bamtan** [borishonman/cydownload#2]
Hi, I cannot open the following repository: 

https://beta.unlimapps.com

```Getting repo information...
No Release file could be found, repo information will be blank
Getting package list...
Error transferring https://beta.unlimapps.com/dists/stable/main/binary-iphoneos-arm/Packages.bz2 - server replied: Not Found
Not a valid Cydia repository!
```

**Comment by borishonman** [comment]
Was able to reproduce. Trying to identify the cause of this issue now.

**Comment by bamtan** [comment]
Cool, thanks for your work!

**Comment by borishonman** [comment]
Alright, the fix has been implemented. I'm fixing another issue that popped up then I will push a new release.

**Comment by bamtan** [comment]
I can confirm it opens the repo, though I cannot download the .deb file with the following error:

```
Downloading package.deb
Download failed: Protocol "" is unknown
```

**Comment by borishonman** [comment]
Is that happening with every package in that repo or just a few specific ones?

**Comment by bamtan** [comment]
Seems to happen to a few specific ones..

Most of the packages under the System tab get the error message, as well as Tweaks (Facebook ++, Instagram ++). Though it's pretty spread out so I can't check them all.

**Comment by borishonman** [comment]
Ok, that should be fixed. The issue came from certain packages using non-number version tags, which were ignored when it tried to sort the list of versions. Release 1.1.1 has been updated.

**Comment by ghost** [comment]
Working now, thanks for the fix!
