### ISSUE TITLE
Accessing authenticate only repos

### ISSUE THREAD

**Issue by agates4** [borishonman/cydownload#3]
<img width="1152" alt="screen shot 2018-02-05 at 12 19 06 pm" src="https://user-images.githubusercontent.com/2314309/35818733-c731f39c-0a6e-11e8-9d16-2706575b9857.png">

Would be nice for a window prompt asking for credentials so we can access locked repos

**Comment by frakman1** [comment]
Or even a way to enter the username/password into the URL like:

`http://username:password@my.repo.url.com/`
