### ISSUE TITLE
[Request] Bulk import of repos

### ISSUE THREAD

**Issue by frakman1** [borishonman/cydownload#9]
It would be nice to import all my repos all at once instead of one-by-one

**Comment by frakman1** [comment]
Is there a plist file somewhere I could manually edit?

**Comment by UInt2048** [comment]
@frakman1 d71f1ae8a9450927ad73db5e1fb4bf3aabe7b909 shows there's a file called `repos.ini`, which is just a list of the repos. On my Mac, it was at `~/Library/Application Support/cydownload/repos.ini`.

**Comment by frakman1** [comment]
Great! I found it there too.
So I can just paste a bunch of repo URLs there.
Thanks!

**Comment by UInt2048** [comment]
@frakman1 Yeah, separated by newlines...
